TestPR/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TestPR.Models;

namespace TestPR.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationContext db;
        public CategoryController(ApplicationContext context)
        {
            db = context;
        }


        // GET: CategoryController
        public ActionResult Index()
        {
            return View(db.Category.ToArray());
        }


        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category cat)
        {
            try
            {
                db.Category.Add(cat);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Category cat = db.Category.Find(id);
            if (cat != null)
            {
                return View(cat);
            }
            return View();
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category cat)
        {
            try
            {
                db.Category.Update(cat);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

     
        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Category cat = db.Category.Find(id);
                if (cat == null)
                {
                    return NotFound();
                }
                db.Category.Remove(cat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TestPR/Controllers/ProductController.cs
using Humanizer.Localisation.TimeToClockNotation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.VisualBasic;
using System.Globalization;
using System.Net;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using TestPR.Models;

namespace TestPR.Controllers
{
    public class ProductController : Controller
    {
        private ApplicationContext db;
        public ProductController(ApplicationContext context) {
            db = context;
        }

        // GET: ProductController
        [HttpGet]
        public ActionResult Index(int? category, string? name)
        {
            IQueryable<Product> pr = db.Product.Include(p => p.category);
            if (category != null && category != 0)
            {
                pr = pr.Where(p => p.categoryId == category);
            }
            if (!string.IsNullOrEmpty(name))
            {
                pr = pr.Where(p => p.Name!.Contains(name));
            }

            List<Category> categories = db.Category.ToList();
            // устанавливаем начальный элемент, который позволит выбрать всех
            categories.Insert(0, new Category { Name = "Все", Id = 0 });

            UserListViewModel viewModel = new UserListViewModel
            {
                Products = pr.ToList(),
                Categories = new SelectList(categories, "Id", "Name", category),
                Name = name
            };
            return View(viewModel);

            //var pr = db.Product.Include(u => u.category).ToList();
            //return View(pr.ToArray());
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Categories = new SelectList(db.Category.ToList(), "Id", "Name");
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product pr)
        {
            try
            {
                db.Product.Add(pr);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");               
            }
            catch
            {
                return View();
            }
        }

       
        [HttpGet]
        public ActionResult Edit(int? id)
        {           
            
            Product pr = db.Product.Find(id);
            if (pr != null)
            {
                ViewBag.Categories = new SelectList(db.Category.ToList(), "Id", "Name");
                return View(pr);
            }
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Product pr)
        {
            try
            {
                db.Product.Update(pr);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                Product pr = db.Product.Find(id);
                if (pr == null)
                {
                    return NotFound();
                }
                db.Product.Remove(pr);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public IActionResult OnGetGetVal()
        {
            return new JsonResult("Founded user");
        }

        [HttpPost]
        public JsonResult AjaxMethod([FromBody] Product product)
        {
            //pr.DateTime = DateTime.Now.ToString();
            return Json(product);
        }

        [HttpPost]
        public string GetValResult(string number1)
        {
            // Текущая дата
            string data = string.Empty;
            // Адрес сайта с курсом валюты
            string url = "https://benefit.by/currency/";
            // HTML сайта с курсом валюты
            string html = string.Empty;
            // Регулярное выражение
            string pattern = "1 Доллар США";
            DateTime today = DateTime.Now;
            data = today.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);

            url += data;

            // Отправляем GET запрос и получаем в ответ HTML-код сайта с курсом валюты
            HttpWebRequest myHttpWebRequest = (HttpWebRequest)HttpWebRequest.Create(url);
            HttpWebResponse myHttpWebResponse = (HttpWebResponse)myHttpWebRequest.GetResponse();
            StreamReader myStreamReader = new StreamReader(myHttpWebResponse.GetResponseStream());
            html = myStreamReader.ReadToEnd();

            int x = html.LastIndexOf(pattern);
            int k = html.IndexOf("</tr>", x);
            string g = html.Substring(x, k - x);
            g = g.Replace("<td>", "").Replace("1 Доллар США", "").Replace("</td>", "").Replace("<br />", "").Replace(" ", "").Replace("@\r\n?|\n", "").Replace("\n", "");

            double r1 = double.Parse(g, CultureInfo.InvariantCulture);
            double r2 = Convert.ToDouble(number1);
            double result = r1 * r2;

            return "В долларах по курсу на " + today.Date.ToShortDateString() + " равен " + result.ToString() +" руб.";
            
        }
    }
}

TestPR/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TestPR.Models;

namespace TestPR.Controllers
{

    [Authorize(Roles = "Администратор")]
    [Route("api/[controller]")]
    [ApiController]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<IdentityRole>>> Get()
        {
            return await _roleManager.Roles.ToListAsync();
        }

        [HttpPost]
        [Produces("application/json")]
        public async Task<IActionResult> Post([FromBody] IdentityRole role)
        {
            return (IActionResult)await _roleManager.CreateAsync(role);               
          
        }



    }
}

TestPR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Каталог товаров</title>
   @*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" type="text/css" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                @* <a class="navbar-brand" href="#">Панель навигации</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                         @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link active" aria-current="page" style="text-decoration:none">
                                @Html.ActionLink("Продукты", "Index", "Product")
                            </a>
                            @if (!User.IsInRole("Простой пользователь"))
                            {
                                <a class="nav-link" style="text-decoration:none">
                                    @Html.ActionLink("Категории", "Index", "Category")
                                </a>
                            }
                        }
                        <div style="flex-grow: revert;display: flex!important;flex-basis: auto; margin-left: 50px">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link" style="text-decoration:none"  asp-area="" asp-controller="Account" asp-action="Login" href="/Account/Login">Вход</a>

                        }
                            @if (User.IsInRole("Администратор"))
                        {
                                <a class="nav-link" href="/swagger/index.html">Переход на админскую часть</a>
                        }
                            @if (User.Identity.IsAuthenticated)
                        {

                            <div class="nav-link" >
                                @Html.ActionLink("Выйти", "Logout", "Account")
                            </div>

                        }
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register" href="/Account/Register">Регистрация</a>

                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link"  style="margin-left: 10px" asp-area="" asp-controller="Account">@User.Identity.Name</a>

                        }
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        @* <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
               
                <nav class="topnav">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index" href="/Event">Мероприятия</a>
                        
                     
                        @if (User.IsInRole("Админ"))
                        {
                        <div class="nav-link">
                            @Html.ActionLink("Список пользователей", "UserList", "Roles")
                        </div>
                        <div class="nav-link">
                            @Html.ActionLink("Список ролей", "Index", "Roles")
                        </div>
                        }
                        @if (!User.Identity.IsAuthenticated)
                        {
                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login" href="/Account/Login">Вход</a>
                            
                        }
                        @if (User.Identity.IsAuthenticated)
                        {

                        <div class="nav-link">
                        @Html.ActionLink("Выйти", "Logout", "Account")</div>
                                                
                        }
                        @if (!User.Identity.IsAuthenticated)
                        {
                                <a class="nav-link text-dark other" asp-area="" asp-controller="Account" asp-action="Register" href="/Account/Register">Регистрация</a>
                           
                        } 
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link" asp-area="" asp-controller="Account">@User.Identity.Name</a>
                        
                    }
                </nav>
            </div>
        </nav> *@
    </header>
    <br />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>

   

   
    @RenderSection("Scripts", required: false)
</body>

</html>
<style>
    a{
        text-decoration: none;
        color: #000;
    }

    btn btn-primary a{
        color: white;
    }

    div#navbarNavAltMarkup {
        background: lightgray;
        padding: 15px;
    }
</style>